### ISSUE TITLE
Создать шаблонный проект на react с UI Kit

### ISSUE THREAD

**Issue by katunilya** [unit-team-spbu/frontend#6]
## Задача

Требуется создать базовый шаблонный проект на React и импортировать туда какой-нибудь UI kit (см. [список популярных](https://blog.logrocket.com/top-10-react-component-libraries-for-2020/))

## Требования к реализации

Создать шаблонный проект под названием `client` в папке репозитория, используя расширение [create-react-app](https://www.npmjs.com/package/create-react-app). Для этого:

* глобально установить пакет `create-react-app` через npm
* используя пакет создать шаблонное React приложение (любой гайд на YouTube)

## To-Do

- [x] создать шаблонный проект react
- [x] выбрать UI kit (отписать какой в комментарии и там же мотивировать выбор)
- [x] установить UI kit в приложение

**Comment by IrinaS-77** [comment]
Выбран Material UI из-за удобства интерфейса и привлекательного дизайна. Так же есть шаблоны в Figma.
